### ISSUE TITLE
Parser output not returned

### ISSUE THREAD

**Issue by pup-shellee** [snyk/rpm-parser#56]
Attempting to use the parser at a base level to see if its useful for us and I cannot get the output to return. The code snippet in the readme does not work it was throwing a bunch of errors associated with await and promises, so I modified it to be this:

import { getPackages } from '@snyk/rpm-parser';
import { readFileSync } from 'fs';
// ...
const rpmDatabase = readFileSync('/var/lib/rpm/Packages');

(async ()=>{
  const result = await getPackages(rpmDatabase);
  console.log(result.response);
})();

Now there are no errors but also no output. Can someone please help?

**Comment by agranado2k** [comment]
Hi @pup-shellee,

You can print `result.error` to see what error you are having here.
```js
const result = await getPackages(rpmDatabase);
console.log("response: ", result.response);
console.log("error: ", result.error);
```

[Link in the code](https://github.com/snyk/rpm-parser/blob/master/lib/index.ts#L45-L48) how the lib returns errors.

**Comment by pup-shellee** [comment]
Hi. I see this issue was closed, however I did as you recommended and still no output.

I saw the methods which return the errors and the output hence the request for assistance. 

I suppose I will try another method, but this issue still exists and we still have no output. Thanks.

**Comment by ivanstanev** [comment]
@pup-shellee Your code probably returns immediately as nothing awaits your async function. You could instead try to wrap it in setImmediate:

```typescript
setImmediate(async () => {
  const result = await getPackages(rpmDatabase);
  console.log(result.response);
});
```

Let me know if that resolved your issue!
